apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vein-k8s.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  serverPassword: {{ .Values.VEIN_SERVER_PASSWORD | b64enc | quote }}
