apiVersion: v1
kind: Service
metadata:
  name: {{ include "vein-k8s.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.networking.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: gameport
      port: {{ .Values.VEIN_GAME_PORT | int }}
      targetPort: {{ .Values.VEIN_GAME_PORT | int }}
      protocol: UDP
      {{- if .Values.networking.nodePort }}
      nodePort: {{ .Values.networking.nodePort | int }}
      {{- end }}
    
    - name: queryport
      port: {{ .Values.VEIN_QUERY_PORT | int }}
      targetPort: {{ .Values.VEIN_QUERY_PORT | int }}
      protocol: UDP
      {{- if .Values.networking.nodePort }}
      nodePort: {{ .Values.networking.nodePort | int }}
      {{- end }}
