apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haven-k8s.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  havenDbPassword: {{ .Values.haven.env.HAVEN_DB_PASSWORD | b64enc | quote }}
  havenUserPassword: {{ .Values.haven.env.HAVEN_USER_PASS | b64enc | quote }}
